config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'bouquets/all', to: 'bouquets#all'
  get 'bouquets/index', to: 'bouquets#index'
  get 'about', to: 'bouquets#about'
  get 'bouquets/new', to: 'bouquets#new'
  get 'bouquets/confirm/:id', to: 'bouquets#confirm'
  get 'bouquets/:id', to: 'bouquets#show'
  post 'bouquets/create', to: 'bouquets#create'
  post 'bouquets/all', to: 'bouquets#all'
  post 'bouquets/locations', to: 'bouquets#locations'
  post 'bouquets/messages', to: 'bouquets#messages'
  delete 'bouquets/:id', to: 'bouquets#destroy'

  post 'spotify_search', to: 'spotify_search#index'
  get '/auth/spotify/callback', to: 'callbacks#spotify'
  post 'search', to: 'spotify_search#search'
  post 'texts/create', to: 'texts#create'
  get 'users/:id', to: 'users#show'

  root 'bouquets#index'

end

app/controllers/spotify_search_controller.rb
class SpotifySearchController < ApplicationController
  def index

  	spotify_url = "https://api.spotify.com/v1/"
    query = params[:search].gsub(/ /, "%20")
    searchURL = "#{spotify_url}search?q=#{query}&type=artist,track&limit=10"
    access_token = ENV['ACCESS_TOKEN']
    # getting client token
    client_token = Base64.strict_encode64(ENV['SPOTIFY_CLIENT_ID'] + ":" + ENV['SPOTIFY_CLIENT_SECRET'])

    spotify_token = RestClient.post("https://accounts.spotify.com/api/token",{"grant_type": "client_credentials"}, {"Authorization": "Basic #{client_token}"})
    parsed_token = JSON.parse(spotify_token)
    # grab the spotify data for the corresponding artist
    response = RestClient.get(searchURL, {"Authorization": "Bearer #{parsed_token["access_token"]}"})
    # return that artist's top tracks

    @artist_data = JSON.parse(response)["artists"]["items"]

    @artist_return = @artist_data.slice(0,10)

    @tracks = JSON.parse(response)["tracks"]["items"]

    #return songs  from search results
    @songs = []
    @tracks.each do |song|
      @songs << { track_id: song["id"],
                  song_title: song["name"],
                  album_name: song["album"]["name"],
                  artists_name: song["artists"][0]["name"]
                  }
    end
     

     top_tracks_results = []
     @artist_return.each do |artist|
      top_tracks_url = "https://api.spotify.com/v1/artists/#{artist["id"]}/top-tracks?country=US&limit=1"
      top_tracks_results << JSON.parse(RestClient.get(top_tracks_url, {"Authorization": "Bearer #{parsed_token["access_token"]}"}))
     end

      @tracks_info = []
      top_tracks_results.each do |track|
         if track["tracks"].length > 0

          @tracks_info << { track_id: track["tracks"][0]["id"],
                            song_title: track["tracks"][0]["name"],
                            album_name: track["tracks"][0]["album"]["name"],
                            artist_name: track["tracks"][0]["artists"][0]["name"] }
        end
       end

    #render json: {tracks: @tracks_info, artist_data: @artist_data}
    render :_results, locals: { artist: @tracks_info, tracks: @songs}, layout: false
  end

end

app/helpers/spotify_search_helper.rb
module SpotifySearchHelper
end

app/views/spotify_search/_results.html.erb
<%if @artist_data != nil %>
<div class="scroll-container nowrap overflow-x-auto ">
<h1 class="artist-cat">Artist</h1>
		<% @tracks_info.each do |track| %>
			<div class="artist-container" id="<%=track[:track_id] %>">
				 <iframe src="https://open.spotify.com/embed?uri=spotify:track:<%=track[:track_id] %>"
				        frameborder="0" allowtransparency="true" width="300" height="380"></iframe>

				 <%  song = {track: track[:song_title] , artist:track[:artist_name] , spotify_id: track[:track_id], album: track[:album_name] } %>
		     <%= button_to "add song to bouquet", bouquets_create_path,  form_class:" add_song_button b ph3 pv2 input-reset ba b--black bg-transparent  pointer f6 dib", params: song  %>
	    </div>
		<% end %>
	<% else %>
	  <h2>Zero results</h2>
	  <%=link_to "search again", bouquets_new_path %>
	<%end %>

<h1 class="track-cat">Tracks</h1>
	<%if @songs != nil %>
				<% @songs.each do |track| %>
	        <div class="track-container" id="<%=track[:track_id] %> data">
						<iframe src="https://open.spotify.com/embed?uri=spotify:track:<%=track[:track_id] %>"
						        frameborder="0" allowtransparency="true" width="300" height="380"></iframe>

				 <%  song = {	track: track[:song_title] , artist: track[:artists_name] , spotify_id: track[:track_id],album: track[:album_name] } %>
		     <%= button_to "add song to bouquet", bouquets_create_path,  form_class:"add_song_button b ph3 pv2 input-reset ba b--black bg-transparent  pointer f6 dib", params: song  %>

					</div>
			<%end %>

	<% else %>
		<h2>Zero results</h2>
	<%end %>
</div>

app/views/spotify_search/_status.html.erb
<article class="pa3 pa5-ns" data-name="slab-stat-large">
  <h3 class="f6 ttu tracked">Today</h3>
  <div class="cf">
    <dl class="db dib-l w-auto-l lh-title mr6-l">
      <dd class="f6 fw4 ml0">Closed Issues</dd>
      <dd class="f2 f-subheadline-l fw6 ml0">1,024</dd>
    </dl>
    <dl class="db dib-l w-auto-l lh-title mr6-l">
      <dd class="f6 fw4 ml0">Open Issues</dd>
      <dd class="f2 f-subheadline-l fw6 ml0">993</dd>
    </dl>
    <dl class="db dib-l w-auto-l lh-title mr6-l">
      <dd class="f6 fw4 ml0">Next Release</dd>
      <dd class="f2 f-subheadline-l fw6 ml0">10-22</dd>
    </dl>
    <dl class="db dib-l w-auto-l lh-title mr6-l">
      <dd class="f6 fw4 ml0">Days Left</dd>
      <dd class="f2 f-subheadline-l fw6 ml0">4</dd>
    </dl>
    <dl class="db dib-l w-auto-l lh-title mr6-l">
      <dd class="f6 fw4 ml0">Favorite Cat</dd>
      <dd class="f2 f-subheadline-l fw6 ml0">All of Them</dd>
    </dl>
    <dl class="db dib-l w-auto-l lh-title">
      <dd class="f6 fw4 ml0">App Downloads</dd>
      <dd class="f2 f-subheadline-l fw6 ml0">1,200</dd>
    </dl>
  </div>
</article>

app/views/spotify_search/search.html.erb
<% form_tag spotify_search_path, :method => 'get' do %>
  <p>
    <%= select_tag(:search_type, options_for_select([["artist"],["track"]])) %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>